window.LEAGUE_copalib = [
  { name: "Racing Club", short: "RAC", country: "Argentina", image: "clubs/copalib/racingclub.png" },
  { name: "Vélez Sarsfield", short: "VEL", country: "Argentina", image: "clubs/copalib/velez.png" },
  { name: "Estudiantes", short: "EST", country: "Argentina", image: "clubs/copalib/estudiantes.png" },
  { name: "Central Córdoba", short: "CCO", country: "Argentina", image: "clubs/copalib/cordoba.png" },
  { name: "Talleres", short: "TAL", country: "Argentina", image: "clubs/copalib/talleres.png" },
  { name: "River Plate", short: "RIV", country: "Argentina", image: "clubs/copalib/riverplate.png" },
  { name: "Boca Juniors", short: "BOC", country: "Argentina", image: "clubs/copalib/bocajuniors.png" },
  { name: "San Antonio Bulo Bulo", short: "SAB", country: "Bolivia", image: "clubs/copalib/sanantonio.png" },
  { name: "Bolívar", short: "BOL", country: "Bolivia", image: "clubs/copalib/bolivar.png" },
  { name: "The Strongest", short: "STR", country: "Bolivia", image: "clubs/copalib/thestrongest.png" },
  { name: "Blooming", short: "BLO", country: "Bolivia", image: "clubs/copalib/blooming.png" },
  { name: "Botafogo", short: "BOT", country: "Brazil", image: "clubs/copalib/botafogo.png" },
  { name: "Flamengo", short: "FLA", country: "Brazil", image: "clubs/copalib/flamengo.png" },
  { name: "Palmeiras", short: "PAL", country: "Brazil", image: "clubs/copalib/palmeiras.png" },
  { name: "Fortaleza", short: "FOR", country: "Brazil", image: "clubs/copalib/fortaleza.png" },
  { name: "Internacional", short: "INT", country: "Brazil", image: "clubs/copalib/internacional.png" },
  { name: "São Paulo", short: "SAO", country: "Brazil", image: "clubs/copalib/saopaulo.png" },
  { name: "Corinthians", short: "COR", country: "Brazil", image: "clubs/copalib/corinthians.png" },
  { name: "Bahia", short: "BAH", country: "Brazil", image: "clubs/copalib/bahia.png" },
  { name: "Colo-Colo", short: "COL", country: "Chile", image: "clubs/copalib/colocolo.png" },
  { name: "Universidad de Chile", short: "UCH", country: "Chile", image: "clubs/copalib/uofchile.png" },
  { name: "Deportes Iquique", short: "IQU", country: "Chile", image: "clubs/copalib/iquique.png" },
  { name: "Ñublense", short: "NUB", country: "Chile", image: "clubs/copalib/nublense.png" },
  { name: "Atlético Bucaramanga", short: "BUC", country: "Colombia", image: "clubs/copalib/bucaramanga.png" },
  { name: "Atlético Nacional", short: "NAC", country: "Colombia", image: "clubs/copalib/nacional.png" },
  { name: "Deportes Tolima", short: "TOL", country: "Colombia", image: "clubs/copalib/tolima.png" },
  { name: "Santa Fe", short: "SFE", country: "Colombia", image: "clubs/copalib/santafe.png" },
  { name: "LDU Quito", short: "LDU", country: "Ecuador", image: "clubs/copalib/lduquito.png" },
  { name: "Independiente del Valle", short: "IDV", country: "Ecuador", image: "clubs/copalib/independiente.png" },
  { name: "Barcelona SC", short: "BSC", country: "Ecuador", image: "clubs/copalib/barcelonaecuador.png" },
  { name: "El Nacional", short: "ELN", country: "Ecuador", image: "clubs/copalib/elnacional.png" },
  { name: "Olimpia", short: "OLI", country: "Paraguay", image: "clubs/copalib/olimpia.png" },
  { name: "Libertad", short: "LIB", country: "Paraguay", image: "clubs/copalib/libertad.png" },
  { name: "Cerro Porteño", short: "CER", country: "Paraguay", image: "clubs/copalib/cerro.png" },
  { name: "Nacional", short: "NAC", country: "Paraguay", image: "clubs/copalib/nacionalpar.png" },
  { name: "Universitario", short: "UNI", country: "Peru", image: "clubs/copalib/universitario.png" },
  { name: "Sporting Cristal", short: "CRI", country: "Peru", image: "clubs/copalib/cristal.png" },
  { name: "Melgar", short: "MEL", country: "Peru", image: "clubs/copalib/melgar.png" },
  { name: "Alianza Lima", short: "ALI", country: "Peru", image: "clubs/copalib/alianza.png" },
  { name: "Peñarol", short: "PEN", country: "Uruguay", image: "clubs/copalib/penarol.png" },
  { name: "Nacional", short: "NAC", country: "Uruguay", image: "clubs/copalib/nacionaluru.png" },
  { name: "Boston River", short: "BOS", country: "Uruguay", image: "clubs/copalib/bostonriver.png" },
  { name: "Defensor Sporting", short: "DEF", country: "Uruguay", image: "clubs/copalib/defensor.png" },
  { name: "Deportivo Táchira", short: "TAC", country: "Venezuela", image: "clubs/copalib/tachira.png" },
  { name: "Carabobo", short: "CAR", country: "Venezuela", image: "clubs/copalib/carabobo.png" },
  { name: "Universidad Central", short: "UCV", country: "Venezuela", image: "clubs/copalib/uc.png" },
  { name: "Monagas", short: "MON", country: "Venezuela", image: "clubs/copalib/monagas.png" },
];