window.LEAGUE_ucl = [
  { name: "Paris Saint-Germain", short: "PSG", country: "France", image: "clubs/UCL/psg.png" },
  { name: "Bayern Munich", short: "BAY", country: "Germany", image: "clubs/UCL/bayern.png" },
  { name: "Inter Milan", short: "INT", country: "Italy", image: "clubs/UCL/inter.png" },
  { name: "Arsenal", short: "ARS", country: "England", image: "clubs/UCL/arsenal.png" },
  { name: "Real Madrid", short: "RMA", country: "Spain", image: "clubs/UCL/madrid.png" },
  { name: "Borussia Dortmund", short: "BVB", country: "Germany", image: "clubs/UCL/bvb.png" },
  { name: "Manchester City", short: "MCI", country: "England", image: "clubs/UCL/manc.png" },
  { name: "Newcastle United", short: "NEW", country: "England", image: "clubs/UCL/newcastle.png" },
  { name: "Barcelona", short: "BAR", country: "Spain", image: "clubs/UCL/barca.png" },
  { name: "Liverpool", short: "LIV", country: "England", image: "clubs/UCL/liverpool.png" },
  { name: "Chelsea", short: "CHE", country: "England", image: "clubs/UCL/chelsea.png" },
  { name: "Sporting CP", short: "SPO", country: "Portugal", image: "clubs/UCL/sporting.png" },
  { name: "Qarabağ", short: "QAR", country: "Azerbaijan", image: "clubs/UCL/qarabag.png" },
  { name: "Galatasaray", short: "GAL", country: "Türkiye", image: "clubs/UCL/galatasaray.png" },
  { name: "Tottenham Hotspur", short: "TOT", country: "England", image: "clubs/UCL/spurs.png" },
  { name: "PSV Eindhoven", short: "PSV", country: "Netherlands", image: "clubs/UCL/psv.png" },
  { name: "Atalanta", short: "ATA", country: "Italy", image: "clubs/UCL/atalanta.png" },
  { name: "Marseille", short: "MAR", country: "France", image: "clubs/UCL/marseille.png" },
  { name: "Atlético Madrid", short: "ATM", country: "Spain", image: "clubs/UCL/atletico.png" },
  { name: "Club Brugge", short: "BRU", country: "Belgium", image: "clubs/UCL/brugge.png" },
  { name: "Athletic Bilbao", short: "ATH", country: "Spain", image: "clubs/UCL/bilbao.png" },
  { name: "Eintracht Frankfurt", short: "FRA", country: "Germany", image: "clubs/UCL/frankfurt.png" },
  { name: "Napoli", short: "NAP", country: "Italy", image: "clubs/UCL/napoli.png" },
  { name: "Union Saint-Gilloise", short: "USG", country: "Belgium", image: "clubs/UCL/usg.png" },
  { name: "Juventus", short: "JUV", country: "Italy", image: "clubs/UCL/juve.png" },
  { name: "Bodø/Glimt", short: "BOD", country: "Norway", image: "clubs/UCL/bodo.png" },
  { name: "Monaco", short: "MON", country: "France", image: "clubs/UCL/monaco.png" },
  { name: "Slavia Prague", short: "SLA", country: "Czechia", image: "clubs/UCL/slavia.png" },
  { name: "Pafos", short: "PAF", country: "Cyprus", image: "clubs/UCL/pafos.png" },
  { name: "Bayer Leverkusen", short: "BAY", country: "Germany", image: "clubs/UCL/bayer.png" },
  { name: "Villarreal", short: "VIL", country: "Spain", image: "clubs/UCL/villarreal.png" },
  { name: "Copenhagen", short: "CPH", country: "Denmark", image: "clubs/UCL/copenhagen.png" },
  { name: "Olympiacos", short: "OLY", country: "Greece", image: "clubs/UCL/olympiacos.png" },
  { name: "Kairat", short: "KAI", country: "Kazakhstan", image: "clubs/UCL/kairat.png" },
  { name: "Benfica", short: "BEN", country: "Portugal", image: "clubs/UCL/benfica.png" },
  { name: "Ajax", short: "AJA", country: "Netherlands", image: "clubs/UCL/ajax.png" }
];