window.LEAGUE_uel = [
  { name: "Roma", short: "ROM", country: "Italy", image: "clubs/UEL/roma.png" },
  { name: "Porto", short: "POR", country: "Portugal", image: "clubs/UEL/porto.png" },
  { name: "Rangers", short: "RAN", country: "Scotland", image: "clubs/UEL/rangers.png" },
  { name: "Feyenoord", short: "FEY", country: "Netherlands", image: "clubs/UEL/feyenoord.png" },
  { name: "Lille", short: "LIL", country: "France", image: "clubs/UEL/losc.png" },
  { name: "Dinamo Zagreb", short: "DIN", country: "Croatia", image: "clubs/UEL/zagreb.png" },
  { name: "Real Betis", short: "BET", country: "Spain", image: "clubs/UEL/betis.png" },
  { name: "Red Bull Salzburg", short: "SAL", country: "Austria", image: "clubs/UEL/salzburg.png" },
  { name: "Aston Villa", short: "AVL", country: "England", image: "clubs/UEL/villa.png" },
  { name: "Fenerbahçe", short: "FEN", country: "Türkiye", image: "clubs/UEL/fenerbahce.png" },
  { name: "Braga", short: "BRA", country: "Portugal", image: "clubs/UEL/braga.png" },
  { name: "Red Star Belgrade", short: "RSD", country: "Serbia", image: "clubs/UEL/redstar.png" },
  { name: "Lyon", short: "LYO", country: "France", image: "clubs/UEL/ol.png" },
  { name: "PAOK", short: "PAO", country: "Greece", image: "clubs/UEL/paok.png" },
  { name: "Viktoria Plzeň", short: "VIK", country: "Czechia", image: "clubs/UEL/plzen.png" },
  { name: "Ferencváros", short: "FER", country: "Hungary", image: "clubs/UEL/feren.png" },
  { name: "Celtic", short: "CEL", country: "Scotland", image: "clubs/UEL/celtic.png" },
//{ name: "Maccabi Tel Aviv", short: "MAC", country: "Occupied Palestine", image: "clubs/UEL/mta.png" },
  { name: "Young Boys", short: "YBO", country: "Switzerland", image: "clubs/UEL/yb.png" },
  { name: "Basel", short: "BAS", country: "Switzerland", image: "clubs/UEL/basel.png" },
  { name: "Midtjylland", short: "MID", country: "Denmark", image: "clubs/UEL/midtjylland.png" },
  { name: "Freiburg", short: "FRE", country: "Germany", image: "clubs/UEL/freiburg.png" },
  { name: "Ludogorets Razgrad", short: "LUD", country: "Bulgaria", image: "clubs/UEL/ludogorets.png" },
  { name: "Nottingham Forest", short: "NFO", country: "England", image: "clubs/UEL/forest.png" },
  { name: "Sturm Graz", short: "STU", country: "Austria", image: "clubs/UEL/sturm.png" },
  { name: "FCSB", short: "FCS", country: "Romania", image: "clubs/UEL/fcsb.png" },
  { name: "Nice", short: "NIC", country: "France", image: "clubs/UEL/nice.png" },
  { name: "Bologna", short: "BOL", country: "Italy", image: "clubs/UEL/bologna.png" },
  { name: "Celta Vigo", short: "CEL", country: "Spain", image: "clubs/UEL/celta.png" },
  { name: "Stuttgart", short: "STU", country: "Germany", image: "clubs/UEL/stuttgart.png" },
  { name: "Panathinaikos", short: "PAN", country: "Greece", image: "clubs/UEL/panathinaikos.png" },
  { name: "Malmö", short: "MAL", country: "Sweden", image: "clubs/UEL/malmo.png" },
  { name: "Go Ahead Eagles", short: "GAE", country: "Netherlands", image: "clubs/UEL/gae.png" },
  { name: "Utrecht", short: "UTC", country: "Netherlands", image: "clubs/UEL/utrecht.png" },
  { name: "Genk", short: "GEN", country: "Belgium", image: "clubs/UEL/genk.png" },
  { name: "Brann", short: "BRA", country: "Norway", image: "clubs/UEL/brann.png" }
];
