window.LEAGUE_bundesliga = [
  { name: "Bayern Munich", short: "FCB", image: "images/GER/BL/bayern.png" },
  { name: "Borussia Dortmund", short: "BVB", image: "images/GER/BL/bvb.png" },
  { name: "Bayer Leverkusen", short: "B04", image: "images/GER/BL/b04.png" },
  { name: "RB Leipzig", short: "RBL", image: "images/GER/BL/leipzig.png" },
  { name: "Eintracht Frankfurt", short: "SGE", image: "images/GER/BL/frankfurt.png" },
  { name: "VfB Stuttgart", short: "VFB", image: "images/GER/BL/stuttgart.png" },
  { name: "VfL Wolfsburg", short: "WOB", image: "images/GER/BL/wolfsburg.png" },
  { name: "Werder Bremen", short: "SVW", image: "images/GER/BL/wb.png" },
  { name: "TSG Hoffenheim", short: "TSG", image: "images/GER/BL/hoffenheim.png" },
  { name: "Borussia Mönchengladbach", short: "BMG", image: "images/GER/BL/gladbach.png" },
  { name: "Union Berlin", short: "FCU", image: "images/GER/BL/ub.png" },
  { name: "FC Augsburg", short: "FCA", image: "images/GER/BL/augsburg.png" },
  { name: "1. FC Köln", short: "KOE", image: "images/GER/BL/koln.png" },
  { name: "SC Freiburg", short: "SCF", image: "images/GER/BL/freiburg.png" },
  { name: "Mainz 05", short: "M05", image: "images/GER/BL/mainz.png" },
  { name: "Hamburger SV", short: "HSV", image: "images/GER/BL/hamburger.png" },
  { name: "1. FC Heidenheim", short: "HDH", image: "images/GER/BL/fch.png" },
  { name: "FC St. Pauli", short: "STP", image: "images/GER/BL/pauli.png" }
];
