window.LEAGUE_bundesliga2 = [
  { name: "Hertha BSC", short: "BSC", image: "images/GER/BL2/hertha.png" },
  { name: "Hannover 96", short: "H96", image: "images/GER/BL2/hannover.png" },
  { name: "Arminia Bielefeld", short: "BIE", image: "images/GER/BL2/bielefeld.png" },
  { name: "VfL Bochum", short: "BOC", image: "images/GER/BL2/bochum.png" },
  { name: "Eintracht Braunschweig", short: "EBS", image: "images/GER/BL2/eintracht.png" },
  { name: "Darmstadt 98", short: "D98", image: "images/GER/BL2/darmstadt.png" },
  { name: "Dynamo Dresden", short: "DYN", image: "images/GER/BL2/dresden.png" },
  { name: "Fortuna Düsseldorf", short: "F95", image: "images/GER/BL2/dusseldorf.png" },
  { name: "SV Elversberg", short: "ELV", image: "images/GER/BL2/elversberg.png" },
  { name: "Greuther Fürth", short: "FUR", image: "images/GER/BL2/greuther.png" },
  { name: "Karlsruher SC", short: "KSC", image: "images/GER/BL2/karlsruher.png" },
  { name: "Preußen Münster", short: "PMU", image: "images/GER/BL2/prussia.png" },
  { name: "1. FC Kaiserslautern", short: "FCK", image: "images/GER/BL2/1fck.png" },
  { name: "Schalke 04", short: "S04", image: "images/GER/BL2/s04.png" },
  { name: "SC Paderborn 07", short: "PAD", image: "images/GER/BL2/paderborn.png" },
  { name: "Holstein Kiel", short: "KIE", image: "images/GER/BL2/holsteinkiel.png" },
  { name: "1. FC Magdeburg", short: "MAG", image: "images/GER/BL2/magdeburg.png" },
  { name: "1. FC Nürnberg", short: "FCN", image: "images/GER/BL2/nurnberg.png" }
];
