window.LEAGUE_championship = [
  { name: "Birmingham City", short: "BIR", image: "images/ENG/CH/birmingham.png" },
  { name: "Blackburn Rovers", short: "BLB", image: "images/ENG/CH/blackburn.png" },
  { name: "Bristol City", short: "BRC", image: "images/ENG/CH/bristol.png" },
  { name: "Charlton Athletic", short: "CHA", image: "images/ENG/CH/charlton.png" },
  { name: "Coventry City", short: "COV", image: "images/ENG/CH/coventry.png" },
  { name: "Derby County", short: "DER", image: "images/ENG/CH/derby.png" },
  { name: "Hull City", short: "HUL", image: "images/ENG/CH/hull.png" },
  { name: "Ipswich Town", short: "IPS", image: "images/ENG/CH/ipswich.png" },
  { name: "Leicester City", short: "LEI", image: "images/ENG/CH/leicester.png" },
  { name: "Middlesbrough", short: "MID", image: "images/ENG/CH/middlesbrough.png" },
  { name: "Millwall", short: "MIL", image: "images/ENG/CH/millwall.png" },
  { name: "Norwich City", short: "NOR", image: "images/ENG/CH/norwich.png" },
  { name: "Oxford United", short: "OXF", image: "images/ENG/CH/oxford.png" },
  { name: "Portsmouth", short: "POR", image: "images/ENG/CH/portsmouth.png" },
  { name: "Preston North End", short: "PRE", image: "images/ENG/CH/preston.png" },
  { name: "Queens Park Rangers", short: "QPR", image: "images/ENG/CH/qpr.png" },
  { name: "Sheffield United", short: "SHU", image: "images/ENG/CH/sheffutd.png" },
  { name: "Sheffield Wednesday", short: "SHW", image: "images/ENG/CH/sheffwed.png" },
  { name: "Southampton", short: "SOU", image: "images/ENG/CH/southampton.png" },
  { name: "Stoke City", short: "STK", image: "images/ENG/CH/stoke.png" },
  { name: "Swansea City", short: "SWA", image: "images/ENG/CH/swansea.png" },
  { name: "Watford", short: "WAT", image: "images/ENG/CH/watford.png" },
  { name: "West Bromwich Albion", short: "WBA", image: "images/ENG/CH/wbalbion.png" },
  { name: "Wrexham", short: "WRX", image: "images/ENG/CH/wrexham.png" }
];
