window.LEAGUE_laliga2 = [
  { name: "Albacete", short: "ALB", image: "images/albacete.png" },
  { name: "Almería", short: "ALM", image: "images/almeria.png" },
  { name: "Andorra", short: "AND", image: "images/andorra.png" },
  { name: "Burgos", short: "BUR", image: "images/burgos.png" },
  { name: "Cádiz", short: "CAD", image: "images/cadiz.png" },
  { name: "Castellón", short: "CAS", image: "images/castellon.png" },
  { name: "Ceuta", short: "CEU", image: "images/adc.png" },
  { name: "Córdoba", short: "COR", image: "images/cordoba.png" },
  { name: "Cultural Leonesa", short: "CLE", image: "images/culturalleonesa.png" },
  { name: "Deportivo La Coruña", short: "DEP", image: "images/dlc.png" },
  { name: "Eibar", short: "EIB", image: "images/eibar.png" },
  { name: "Granada", short: "GRA", image: "images/granada.png" },
  { name: "Huesca", short: "HUE", image: "images/huesca.png" },
  { name: "Las Palmas", short: "LPA", image: "images/laspalmas.png" },
  { name: "Leganés", short: "LEG", image: "images/leganes.png" },
  { name: "Málaga", short: "MAL", image: "images/malaga.png" },
  { name: "Mirandés", short: "MIR", image: "images/mirandes.png" },
  { name: "Racing Santander", short: "RAC", image: "images/racingsantander.png" },
  { name: "Real Sociedad B", short: "RSB", image: "images/sociedad.png" },
  { name: "Sporting Gijón", short: "SPG", image: "images/gijon.png" },
  { name: "Real Valladolid", short: "VLL", image: "images/realvalladolid.png" },
  { name: "Real Zaragoza", short: "ZAR", image: "images/realzaragoza.png" }
];
