window.LEAGUE_laliga2 = [
  { name: "Albacete", short: "ALB", image: "images/ESP/LL-SD/albacete.png" },
  { name: "Almería", short: "ALM", image: "images/ESP/LL-SD/almeria.png" },
  { name: "Andorra", short: "AND", image: "images/ESP/LL-SD/andorra.png" },
  { name: "Burgos", short: "BUR", image: "images/ESP/LL-SD/burgos.png" },
  { name: "Cádiz", short: "CAD", image: "images/ESP/LL-SD/cadiz.png" },
  { name: "Castellón", short: "CAS", image: "images/ESP/LL-SD/castellon.png" },
  { name: "Ceuta", short: "CEU", image: "images/ESP/LL-SD/adc.png" },
  { name: "Córdoba", short: "COR", image: "images/ESP/LL-SD/cordoba.png" },
  { name: "Cultural Leonesa", short: "CLE", image: "images/ESP/LL-SD/culturalleonesa.png" },
  { name: "Deportivo La Coruña", short: "DEP", image: "images/ESP/LL-SD/dlc.png" },
  { name: "Eibar", short: "EIB", image: "images/ESP/LL-SD/eibar.png" },
  { name: "Granada", short: "GRA", image: "images/ESP/LL-SD/granada.png" },
  { name: "Huesca", short: "HUE", image: "images/ESP/LL-SD/huesca.png" },
  { name: "Las Palmas", short: "LPA", image: "images/ESP/LL-SD/laspalmas.png" },
  { name: "Leganés", short: "LEG", image: "images/ESP/LL-SD/leganes.png" },
  { name: "Málaga", short: "MAL", image: "images/ESP/LL-SD/malaga.png" },
  { name: "Mirandés", short: "MIR", image: "images/ESP/LL-SD/mirandes.png" },
  { name: "Racing Santander", short: "RAC", image: "images/ESP/LL-SD/racingsantander.png" },
  { name: "Real Sociedad B", short: "RSB", image: "images/ESP/LL-PD/sociedad.png" },
  { name: "Sporting Gijón", short: "SPG", image: "images/ESP/LL-SD/gijon.png" },
  { name: "Real Valladolid", short: "VLL", image: "images/ESP/LL-SD/realvalladolid.png" },
  { name: "Real Zaragoza", short: "ZAR", image: "images/ESP/LL-SD/realzaragoza.png" }
];
