window.LEAGUE_laliga = [
  { name: "Real Madrid", short: "RMA", image: "images/ESP/LL-PD/madrid.png" },
  { name: "Barcelona", short: "BAR", image: "images/ESP/LL-PD/barca.png" },
  { name: "Atlético de Madrid", short: "ATM", image: "images/ESP/LL-PD/atleti.png" },
  { name: "Athletic Bilbao", short: "ATH", image: "images/ESP/LL-PD/bilbao.png" },
  { name: "Real Sociedad", short: "RSO", image: "images/ESP/LL-PD/sociedad.png" },
  { name: "Villarreal", short: "VIL", image: "images/ESP/LL-PD/villarreal.png" },
  { name: "Sevilla", short: "SEV", image: "images/ESP/LL-PD/sevilla.png" },
  { name: "Real Betis", short: "BET", image: "images/ESP/LL-PD/betis.png" },
  { name: "Valencia", short: "VAL", image: "images/ESP/LL-PD/valencia.png" },
  { name: "Girona", short: "GIR", image: "images/ESP/LL-PD/girona.png" },
  { name: "Celta de Vigo", short: "CEL", image: "images/ESP/LL-PD/celta.png" },
  { name: "Getafe", short: "GET", image: "images/ESP/LL-PD/getafe.png" },
  { name: "Rayo Vallecano", short: "RAY", image: "images/ESP/LL-PD/rv.png" },
  { name: "Mallorca", short: "MLL", image: "images/ESP/LL-PD/mallorca.png" },
  { name: "Levante", short: "LEV", image: "images/ESP/LL-PD/levante.png" },
  { name: "Elche", short: "ELC", image: "images/ESP/LL-PD/elche.png" },
  { name: "Oviedo", short: "OVI", image: "images/ESP/LL-PD/oviedo.png" },
  { name: "Alavés", short: "ALA", image: "images/ESP/LL-PD/alaves.png" },
  { name: "Osasuna", short: "OSA", image: "images/ESP/LL-PD/osasuna.png" },
  { name: "Espanyol", short: "ESP", image: "images/ESP/LL-PD/espanyol.png" }
];
