window.LEAGUE_league1 = [
  { name: "Cardiff City", short: "CC", image: "images/cardiff.png" },
  { name: "Huddersfield Town", short: "HT", image: "images/huddersfield.png" },
  { name: "Bolton Wanderers", short: "BW", image: "images/bolton.png" },
  { name: "Plymouth Argyle", short: "PA", image: "images/plymouth.png" },
  { name: "Blackpool", short: "B", image: "images/blackpool.png" },
  { name: "Wigan Athletic", short: "WA", image: "images/wigan.png" },
  { name: "Leyton Orient", short: "LO", image: "images/leyton.png" },
  { name: "Reading", short: "R", image: "images/reading.png" },
  { name: "Rotherham United", short: "RU", image: "images/rotherham.png" },
  { name: "Barnsley", short: "B", image: "images/barnsley.png" },
  { name: "Stevenage", short: "S", image: "images/stevenage.png" },
  { name: "Exeter City", short: "EC", image: "images/exeter.png" },
  { name: "Doncaster Rovers", short: "DR", image: "images/doncaster.png" },
  { name: "Bradford City", short: "BC", image: "images/bradford.png" },
  { name: "Mansfield Town", short: "MT", image: "images/mansfield.png" },
  { name: "AFC Wimbledon", short: "AW", image: "images/afcw.png" },
  { name: "Northampton Town", short: "NT", image: "images/northampton.png" },
  { name: "Stockport County", short: "SC", image: "images/stockport.png" },
  { name: "Port Vale", short: "PV", image: "images/portvale.png" },
];
