window.LEAGUE_league2= [
  { name: "Accrington Stanley", short: "ACC", image: "images/ENG/LT/stanley.png" },
  { name: "Barnet", short: "BRT", image: "images/ENG/LT/barnet.png" },
  { name: "Barrow", short: "BRW", image: "images/ENG/LT/barrow.png" },
  { name: "Bristol Rovers", short: "BRS", image: "images/ENG/LT/bristolrovers.png" },
  { name: "Bromley", short: "BRO", image: "images/ENG/LT/bromley.png" },
  { name: "Cambridge United", short: "CAM", image: "images/ENG/LT/cu.png" },
  { name: "Cheltenham Town", short: "CTO", image: "images/ENG/LT/cheltenham.png" },
  { name: "Chesterfield", short: "CHE", image: "images/ENG/LT/chesterfield.png" },
  { name: "Colchester United", short: "COL", image: "images/ENG/LT/colchester.png" },
  { name: "Crawley Town", short: "CRT", image: "images/ENG/LT/crawley.png" },
  { name: "Crewe Alexandra", short: "CRE", image: "images/ENG/LT/crewe.png" },
  { name: "Fleetwood Town", short: "FLE", image: "images/ENG/LT/fleetwood.png" },
  { name: "Gillingham", short: "GIL", image: "images/ENG/LT/gillingham.png" },
  { name: "Grimsby Town", short: "GRI", image: "images/ENG/LT/grimsby.png" },
  { name: "Harrogate Town", short: "HAR", image: "images/ENG/LT/harrogate.png" },
  { name: "MK Dons", short: "MKD", image: "images/ENG/LT/mkdons.png" },
  { name: "Newport County", short: "NEW", image: "images/ENG/LT/newport.png" },
  { name: "Notts County", short: "NOT", image: "images/ENG/LT/notts.png" },
  { name: "Oldham Athletic", short: "OLD", image: "images/ENG/LT/oldham.png" },
  { name: "Salford City", short: "SAL", image: "images/ENG/LT/salford.png" },
  { name: "Shrewsbury Town", short: "SHR", image: "images/ENG/LT/shrewsbury.png" },
  { name: "Swindon Town", short: "SWI", image: "images/ENG/LT/swindon.png" },
  { name: "Tranmere Rovers", short: "TRA", image: "images/ENG/LT/tranmere.png" },
  { name: "Walsall", short: "WAL", image: "images/ENG/LT/walsall.png" }
];