window.LEAGUE_league1 = [
  { name: "Cardiff City", short: "CAR", image: "images/ENG/LO/cardiff.png" },
  { name: "Huddersfield Town", short: "HUD", image: "images/ENG/LO/huddersfield.png" },
  { name: "Bolton Wanderers", short: "BOL", image: "images/ENG/LO/bolton.png" },
  { name: "Plymouth Argyle", short: "PLY", image: "images/ENG/LO/plymouth.png" },
  { name: "Blackpool", short: "BLA", image: "images/ENG/LO/blackpool.png" },
  { name: "Wigan Athletic", short: "WIG", image: "images/ENG/LO/wigan.png" },
  { name: "Leyton Orient", short: "LEY", image: "images/ENG/LO/leyton.png" },
  { name: "Reading", short: "REA", image: "images/ENG/LO/reading.png" },
  { name: "Rotherham United", short: "ROT", image: "images/ENG/LO/rotherham.png" },
  { name: "Barnsley", short: "BAR", image: "images/ENG/LO/barnsley.png" },
  { name: "Stevenage", short: "STE", image: "images/ENG/LO/stevenage.png" },
  { name: "Exeter City", short: "EXE", image: "images/ENG/LO/exeter.png" },
  { name: "Doncaster Rovers", short: "DON", image: "images/ENG/LO/doncaster.png" },
  { name: "Bradford City", short: "BRA", image: "images/ENG/LO/bradford.png" },
  { name: "Mansfield Town", short: "MAN", image: "images/ENG/LO/mansfield.png" },
  { name: "AFC Wimbledon", short: "WIM", image: "images/ENG/LO/afcw.png" },
  { name: "Northampton Town", short: "NOR", image: "images/ENG/LO/northampton.png" },
  { name: "Stockport County", short: "STO", image: "images/ENG/LO/stockport.png" },
  { name: "Port Vale", short: "PVA", image: "images/ENG/LO/portvale.png" },
  { name: "Burton Albion", short: "BUR", image: "images/ENG/LO/burton.png" },
  { name: "Lincoln City", short: "LIN", image: "images/ENG/LO/lincoln.png" },
  { name: "Luton Town", short: "LUT", image: "images/ENG/LO/luton.png" },
  { name: "Wycombe Wanderers", short: "WYC", image: "images/ENG/LO/wycombe.png" },
  { name: "Peterborough United", short: "PET", image: "images/ENG/LO/peterborough.png" }
];