window.LEAGUE_league2= [
  { name: "Accrington Stanley", short: "AS", image: "images/stanley.png" },
  { name: "Barnet", short: "B", image: "images/barnet.png" },
  { name: "Barrow", short: "B", image: "images/barrow.png" },
  { name: "Bristol Rovers", short: "BR", image: "images/bristolrovers.png" },
  { name: "Bromley", short: "B", image: "images/bromley.png" },
  { name: "Cambridge United", short: "CU", image: "images/cu.png" },
  { name: "Cheltenham Town", short: "CT", image: "images/cheltenham.png" },
  { name: "Chesterfield", short: "C", image: "images/chesterfield.png" },
  { name: "Colchester United", short: "CU", image: "images/colchester.png" },
  { name: "Crawley Town", short: "CT", image: "images/crawley.png" },
  { name: "Crewe Alexandra", short: "CA", image: "images/crewe.png" },
  { name: "Fleetwood Town", short: "FT", image: "images/fleetwood.png" },
  { name: "Gillingham", short: "G", image: "images/gillingham.png" },
  { name: "Grimsby Town", short: "GT", image: "images/grimsby.png" },
  { name: "Harrogate Town", short: "HT", image: "images/harrogate.png" },
  { name: "Milton Keynes Dons", short: "MK", image: "images/mkdons.png" },
  { name: "Newport County", short: "NC", image: "images/newport.png" },
  { name: "Notts County", short: "NC", image: "images/notts.png" },
  { name: "Oldham Athletic", short: "OA", image: "images/oldham.png" },
  { name: "Salford City", short: "SC", image: "images/salford.png" },
];
