window.LEAGUE_ligaprofesional = [
  { name: "Aldosivi", short: "ALD", image: "images/ARG/LP/aldosivi.png" },
  { name: "Argentinos Juniors", short: "AJ", image: "images/ARG/LP/juniors.png" },
  { name: "Atlético Tucumán", short: "ATU", image: "images/ARG/LP/atletico.png" },
  { name: "Banfield", short: "BAN", image: "images/ARG/LP/banfield.png" },
  { name: "Barracas Central", short: "BAR", image: "images/ARG/LP/barracas.png" },
  { name: "Belgrano", short: "BEL", image: "images/ARG/LP/belgrano.png" },
  { name: "Boca Juniors", short: "BOC", image: "images/ARG/LP/bocajuniors.png" },
  { name: "Central Córdoba", short: "CCS", image: "images/ARG/LP/cordoba.png" },
  { name: "Defensa y Justicia", short: "DYJ", image: "images/ARG/LP/dyj.png" },
  { name: "Deportivo Riestra", short: "RIE", image: "images/ARG/LP/riestra.png" },
  { name: "Estudiantes", short: "EST", image: "images/ARG/LP/estudiantes.png" },
  { name: "Gimnasia y Esgrima", short: "GIM", image: "images/ARG/LP/gimnasia.png" },
  { name: "Godoy Cruz", short: "GOD", image: "images/ARG/LP/godoy.png" },
  { name: "Huracán", short: "HUR", image: "images/ARG/LP/huracan.png" },
  { name: "Independiente", short: "IND", image: "images/ARG/LP/independiente.png" },
  { name: "Independiente Rivadavia", short: "INDRIV", image: "images/ARG/LP/rivadavia.png" },
  { name: "Instituto", short: "INS", image: "images/ARG/LP/instituto.png" },
  { name: "Lanús", short: "LAN", image: "images/ARG/LP/lanus.png" },
  { name: "Newell's Old Boys", short: "NOB", image: "images/ARG/LP/nob.png" },
  { name: "Platense", short: "PLA", image: "images/ARG/LP/platense.png" },
  { name: "Racing Club", short: "RAC", image: "images/ARG/LP/racingclub.png" },
  { name: "River Plate", short: "RIV", image: "images/ARG/LP/riverplate.png" },
  { name: "Rosario Central", short: "RC", image: "images/ARG/LP/rosario.png" },
  { name: "San Lorenzo", short: "SLO", image: "images/ARG/LP/sanlorenzo.png" },
  { name: "San Martín", short: "SM", image: "images/ARG/LP/sanmartin.png" },
  { name: "Sarmiento", short: "SAR", image: "images/ARG/LP/sarmiento.png" },
  { name: "Talleres", short: "TAL", image: "images/ARG/LP/talleres.png" },
  { name: "Tigre", short: "TIG", image: "images/ARG/LP/tigre.png" },
  { name: "Unión", short: "UNI", image: "images/ARG/LP/union.png" },
  { name: "Vélez Sarsfield", short: "VEL", image: "images/ARG/LP/velez.png" }
];