window.LEAGUE_ligue1 = [
  { name: "Paris Saint-Germain", short: "PSG", image: "images/psg.png" },
  { name: "Lyon", short: "OL", image: "images/ol.png" },
  { name: "Lille", short: "LIL", image: "images/losc.png" },
  { name: "Monaco", short: "ASM", image: "images/monaco.png" },
  { name: "Lens", short: "LEN", image: "images/lens.png" },
  { name: "Marseille", short: "OM", image: "images/om.png" },
  { name: "Nice", short: "NCE", image: "images/nice.png" },
  { name: "Nantes", short: "NAN", image: "images/nantes.png" },
  { name: "Rennes", short: "REN", image: "images/rennes.png" },
  { name: "Strasbourg", short: "STR", image: "images/strasbourg.png" },
  { name: "Angers", short: "ANG", image: "images/angers.png" },
  { name: "Auxerre", short: "AUX", image: "images/auxerre.png" },
  { name: "Brest", short: "BRE", image: "images/brest.png" },
  { name: "Le Havre", short: "HAC", image: "images/lehavre.png" },
  { name: "Lorient", short: "LOR", image: "images/lorient.png" },
  { name: "Metz", short: "MET", image: "images/metz.png" },
  { name: "Paris FC", short: "PFC", image: "images/parisfc.png" },
  { name: "Toulouse", short: "TOU", image: "images/toulouse.png" }
];
