window.LEAGUE_ligue1 = [
  { name: "Paris Saint-Germain", short: "PSG", image: "images/FRA/L1/psg.png" },
  { name: "Lyon", short: "OL", image: "images/FRA/L1/ol.png" },
  { name: "Lille", short: "LIL", image: "images/FRA/L1/losc.png" },
  { name: "Monaco", short: "ASM", image: "images/FRA/L1/monaco.png" },
  { name: "Lens", short: "LEN", image: "images/FRA/L1/lens.png" },
  { name: "Marseille", short: "OM", image: "images/FRA/L1/om.png" },
  { name: "Nice", short: "NCE", image: "images/FRA/L1/nice.png" },
  { name: "Nantes", short: "NAN", image: "images/FRA/L1/nantes.png" },
  { name: "Rennes", short: "REN", image: "images/FRA/L1/rennes.png" },
  { name: "Strasbourg", short: "STR", image: "images/FRA/L1/strasbourg.png" },
  { name: "Angers", short: "ANG", image: "images/FRA/L1/angers.png" },
  { name: "Auxerre", short: "AUX", image: "images/FRA/L1/auxerre.png" },
  { name: "Brest", short: "BRE", image: "images/FRA/L1/brest.png" },
  { name: "Le Havre", short: "HAC", image: "images/FRA/L1/lehavre.png" },
  { name: "Lorient", short: "LOR", image: "images/FRA/L1/lorient.png" },
  { name: "Metz", short: "MET", image: "images/FRA/L1/metz.png" },
  { name: "Paris FC", short: "PFC", image: "images/FRA/L1/parisfc.png" },
  { name: "Toulouse", short: "TOU", image: "images/FRA/L1/toulouse.png" }
];
