window.LEAGUE_mls = [
  { name: "Atlanta United", short: "ATL", image: "images/USA/MLS/atlanta.png" },
  { name: "Austin FC", short: "AUS", image: "images/USA/MLS/austin.png" },
  { name: "Charlotte FC", short: "CLT", image: "images/USA/MLS/charlotte.png" },
  { name: "Chicago Fire", short: "CHI", image: "images/USA/MLS/chicago.png" },
  { name: "FC Cincinnati", short: "CIN", image: "images/USA/MLS/cincinnati.png" },
  { name: "Colorado Rapids", short: "COL", image: "images/USA/MLS/colorado.png" },
  { name: "Columbus Crew", short: "CLB", image: "images/USA/MLS/columbus.png" },
  { name: "D.C. United", short: "DCU", image: "images/USA/MLS/dc.png" },
  { name: "FC Dallas", short: "DAL", image: "images/USA/MLS/dallas.png" },
  { name: "Houston Dynamo", short: "HOU", image: "images/USA/MLS/houston.png" },
  { name: "Sporting Kansas City", short: "SKC", image: "images/USA/MLS/sporting.png" },
  { name: "LA Galaxy", short: "LAG", image: "images/USA/MLS/lag.png" },
  { name: "Los Angeles FC", short: "LAFC", image: "images/USA/MLS/lafc.png" },
  { name: "Inter Miami", short: "MIA", image: "images/USA/MLS/miami.png" },
  { name: "Minnesota United", short: "MIN", image: "images/USA/MLS/minnesota.png" },
  { name: "CF Montréal", short: "MTL", image: "images/USA/MLS/montreal.png" },
  { name: "Nashville SC", short: "NSH", image: "images/USA/MLS/nashville.png" },
  { name: "New England Revolution", short: "NE", image: "images/USA/MLS/newengrevo.png" },
  { name: "New York City FC", short: "NYC", image: "images/USA/MLS/nyc.png" },
  { name: "New York Red Bulls", short: "RBNY", image: "images/USA/MLS/rbny.png" },
  { name: "Orlando City SC", short: "ORL", image: "images/USA/MLS/orlando.png" },
  { name: "Philadelphia Union", short: "PHI", image: "images/USA/MLS/philadelphia.png" },
  { name: "Portland Timbers", short: "POR", image: "images/USA/MLS/portland.png" },
  { name: "Real Salt Lake", short: "RSL", image: "images/USA/MLS/rsl.png" },
  { name: "San Diego FC", short: "SD", image: "images/USA/MLS/sd.png" },
  { name: "San Jose Earthquakes", short: "SJ", image: "images/USA/MLS/sj.png" },
  { name: "Seattle Sounders", short: "SEA", image: "images/USA/MLS/seattle.png" },
  { name: "St. Louis City SC", short: "STL", image: "images/USA/MLS/stl.png" },
  { name: "Toronto FC", short: "TOR", image: "images/USA/MLS/toronto.png" },
  { name: "Vancouver Whitecaps", short: "VAN", image: "images/USA/MLS/vancouver.png" }
];