window.LEAGUE_premier = [
  { name: "Liverpool", short: "LIV", image: "images/ENG/PL/liverpool.png" },
  { name: "Manchester City", short: "MCI", image: "images/ENG/PL/manc.png" },
  { name: "Arsenal", short: "ARS", image: "images/ENG/PL/arsenal.png" },
  { name: "Chelsea", short: "CHE", image: "images/ENG/PL/chelsea.png" },
  { name: "Tottenham Hotspur", short: "TOT", image: "images/ENG/PL/spurs.png" },
  { name: "Everton", short: "EVE", image: "images/ENG/PL/everton.png" },
  { name: "Manchester United", short: "MUN", image: "images/ENG/PL/manu.png" },
  { name: "Newcastle United", short: "NEW", image: "images/ENG/PL/newcastle.png" },
  { name: "Aston Villa", short: "AVL", image: "images/ENG/PL/villa.png" },
  { name: "Brighton & Hove Albion", short: "BHA", image: "images/ENG/PL/bha.png" },
  { name: "West Ham United", short: "WHU", image: "images/ENG/PL/whu.png" },
  { name: "Bournemouth", short: "BOU", image: "images/ENG/PL/afcb.png" },
  { name: "Crystal Palace", short: "CRY", image: "images/ENG/PL/palace.png" },
  { name: "Brentford", short: "BRE", image: "images/ENG/PL/brentford.png" },
  { name: "Fulham", short: "FUL", image: "images/ENG/PL/fulham.png" },
  { name: "Leeds United", short: "LEE", image: "images/ENG/PL/leeds.png" },
  { name: "Burnley", short: "BUR", image: "images/ENG/PL/burnley.png" },
  { name: "Sunderland", short: "SUN", image: "images/ENG/PL/safc.png" },
  { name: "Wolves", short: "WOL", image: "images/ENG/PL/wolves.png" },
  { name: "Nottingham Forest", short: "NFO", image: "images/ENG/PL/forest.png" }
];
