window.LEAGUE_seriea = [
  { name: "Napoli", short: "NAP", image: "images/ITA/SE-A/napoli.png" },
  { name: "Juventus", short: "JUV", image: "images/ITA/SE-A/juve.png" },
  { name: "Inter Milan", short: "INT", image: "images/ITA/SE-A/inter.png" },
  { name: "AC Milan", short: "MIL", image: "images/ITA/SE-A/milan.png" },
  { name: "AS Roma", short: "ROM", image: "images/ITA/SE-A/roma.png" },
  { name: "Atalanta", short: "ATA", image: "images/ITA/SE-A/atalanta.png" },
  { name: "Lazio", short: "LAZ", image: "images/ITA/SE-A/lazio.png" },
  { name: "Fiorentina", short: "FIO", image: "images/ITA/SE-A/fiorentina.png" },
  { name: "Udinese", short: "UDI", image: "images/ITA/SE-A/udinese.png" },
  { name: "Bologna", short: "BOL", image: "images/ITA/SE-A/bologna.png" },
  { name: "Torino", short: "TOR", image: "images/ITA/SE-A/torino.png" },
  { name: "Sassuolo", short: "SAS", image: "images/ITA/SE-A/sassuolo.png" },
  { name: "Como", short: "COM", image: "images/ITA/SE-A/como.png" },
  { name: "Cremonese", short: "CRE", image: "images/ITA/SE-A/cremonese.png" },
  { name: "Lecce", short: "LEC", image: "images/ITA/SE-A/lecce.png" },
  { name: "Parma", short: "PAR", image: "images/ITA/SE-A/parma.png" },
  { name: "Genoa", short: "GEN", image: "images/ITA/SE-A/genoa.png" },
  { name: "Pisa", short: "PIS", image: "images/ITA/SE-A/pisa.png" },
  { name: "Cagliari", short: "CAG", image: "images/ITA/SE-A/cagliari.png" },
  { name: "Hellas Verona", short: "VER", image: "images/ITA/SE-A/hv.png" }
];
