window.LEAGUE_superlig = [
  { name: "Galatasaray", short: "GAL", image: "images/TUR/SL/galatasaray.png" },
  { name: "Fenerbahçe", short: "FEN", image: "images/TUR/SL/fenerbahce.png" },
  { name: "Beşiktaş", short: "BEŞ", image: "images/TUR/SL/besiktas.png" },
  { name: "Trabzonspor", short: "TRA", image: "images/TUR/SL/trabzonspor.png" },
  { name: "Başakşehir", short: "BAŞ", image: "images/TUR/SL/basaksehir.png" },
  { name: "Eyüpspor", short: "EYÜ", image: "images/TUR/SL/eyupspor.png" },
  { name: "Kasımpaşa", short: "KAS", image: "images/TUR/SL/kasimpasa.png" },
  { name: "Fatih Karagümrük", short: "FAT", image: "images/TUR/SL/fatih.png" },
  { name: "Kocaelispor", short: "KOC", image: "images/TUR/SL/kocaelispor.png" },
  { name: "Gençlerbirliği", short: "GEN", image: "images/TUR/SL/genclerbirligi.png" },
  { name: "Samsunspor", short: "SAM", image: "images/TUR/SL/samsunspor.png" },
  { name: "Göztepe", short: "GÖZ", image: "images/TUR/SL/goztepe.png" },
  { name: "Konyaspor", short: "KON", image: "images/TUR/SL/konyaspor.png" },
  { name: "Rizespor", short: "RIZ", image: "images/TUR/SL/rizespor.png" },
  { name: "Antalyaspor", short: "ANT", image: "images/TUR/SL/antalyaspor.png" },
  { name: "Alanyaspor", short: "ALA", image: "images/TUR/SL/alanyaspor.png" },
  { name: "Kayserispor", short: "KAY", image: "images/TUR/SL/kayserispor.png" },
  { name: "Gaziantep", short: "GAZ", image: "images/TUR/SL/gfk.png" },
];
